[package]
name = "cron-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
